### ISSUE TITLE
Organize Configuration

### ISSUE THREAD

**Issue by majecty** [CodeChain-io/foundry#538]
### TOML configuration file

All configurations described in the TOML configuration file can be customized in CLI arguments.
It has configurations for a node. Each node can change the values in the TOML configuration file freely. It does not affect network behavior.

For example, you can change the port number or data directory in the TOML configuration file.

### Scheme file

Contains configurations for a network. It contains Tendermint parameters and Genesis block information. All nodes in a network should have the same scheme file.

### App descriptor

Contains configurations for modules. It contains information that which modules are used in a network.  It contains configurations for modules.

Some configuration in the app descriptor must be the same in a network. For example, which modules are used. How they are connected must be the same in a network. Some configurations like the number of threads do not affect network behavior.

## Splitting App descriptor to App descriptor and Link descriptor

We have a plan to split the app descriptor file: Foundry configuration (genesis config, transaction services) and general linking instructions (export, import, init config). Let's say the latter as a 'link descriptor'.

See https://github.com/CodeChain-io/foundry/issues/512

## Removing Scheme file

We can think of the content of the scheme file is configurations for the host in the app descriptor. The app descriptor contains the genesis configuration of modules. The scheme file contains the genesis header's information. We don't need to have two configuration files for a genesis block.

## Configuration for network or for node

The current app descriptor has two types of configurations. As I said before, some configurations are for the network, some configurations are for a node.

We didn't discuss yet whether should we split them or how do we split them.

**Comment by majecty** [comment]
# A new configuration draft

## Goal

* Splitting node configuration file and network configuration file.
* Allow users to set module's node configuration files using command-line arguments.

## Node configuration files

config.yml will contain a node's configuration for host and modules.

### Example

```yaml
host:
  mining:
    mem_pool_mem_limit: 512
module-staking:
  thread-pool-size: 16
```

## CLI args

CLI args can change configurations set by the "Node configuration file".

Host parameters will have simple names.
Module's parameters will have a module name prefix

### Example

```sh
$ foundry --mem-pool-mem-limit 512 --staking-thread-pool-size 16
```

### Expected problems

Merging CLI argument config files looks difficult.
We are using clap to parse CLI arguments and YML file to define CLI arguments.
CLAP seems not to provide a way to merge configuration files.

foundry.yml that contains CLI arguments information:
https://github.com/CodeChain-io/foundry/blob/master/foundry/foundry.yml

## App descriptor

The app descriptor will have the same configuration except for imports and exports.

### Example

```yaml
default-sandboxer: single-process

modules:
  module-account:
    hash: a010000000012345678901234567890123456789012345678901234567890123
    init-config:
      thread-pool-size: 16
    tags:
      previliged: true
      
...
```

## Link descriptor

The link descriptor contains imports and exports of modules.

### Example

```yaml
modules:
  module-account:
    hash: a010000000012345678901234567890123456789012345678901234567890123
    exports:
      stateful:
        stateful: {}
      tx-owner:
        tx-owner: {}
      account-manager:
        account-manager: {}
      get-account-and-seq:
        get-account-and-seq: {}
      handle-graphql-request:
        handle-graphql-request: {}
    imports:
      token-manager: module-token/token-manager
```
